name: Publish
on:
  push:
    paths:
    - 'posts/**'
    branches:
    - main

jobs:
  publish_to_storage:
    name: Publish to AZ Blob Storage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true
    - name: Upload Posts
      run: |
        . ./.tools/az/upload-posts.sh "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"