name: Publish
on:
  push:
    # paths:
    # - 'posts/**'
    branches:
    - main
    - rc/publish

jobs:
  publish_to_storage:
    name: Publish to AZ Blob Storage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true
    - name: Publish Posts
      run: |
        . ./.tools/publish.sh "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" ./posts/